target:
	g++ FreqSearch.cxx /Users/tuoyouli/cpplibrary/MyFun.cxx -I${HEADAS}/include -L${HEADAS}/lib -lcfitsio  -o FreqSearch
	./FreqSearch ../testdata/vela_bary.fits
	./FreqSearch ../testdata/P021100601401_he_screen.fits
